/**
 * Каталог объектов
 * Основное отличие версии <b>3.0</b> от <b>2.0</b> в том, что в <b>3.0</b> с помощью одного метода можно получить ответ API сразу со всеми типами данных ­— с организациями, геообъектами, маршрутами и остановками, а не запрашивать данные по разным типам отдельным запросами.
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export default interface ItemsResponseResultAd {
  gta: any;
}
